### PR TITLE
Create gh-pages HTML and Distribution site

### PR DESCRIPTION
**Pull request by wbuchanan**
Should allow users to use:

```
net inst statastan, from("https://stan-dev.github.io/statastan")
```

To install directly from Github.

### CODE REVIEW

**Comment by syclik** [comment]
@robertgrant do you want travis turned on? It looks like travis-ci changed their defaults.

There are a few reasonable options:
1. Have travis not run if it's missing a .travis.yml
2. Have travis not run
3. Include the .travis.yml file that @wbuchanan has added.

I think if we go to option 1 or 2, we should revert `a699d35`.

**Comment by wbuchanan** [comment]
@syclik Do you know if the build would pass with a blank configuration file?  I tried to create the config file just to get it through the CI build but if it would pass with a blank config file that might be the best long term solution (since I'm assuming they won't be supporting Stata).  There is a Stata user who has done some work with Travis CI before (@bquistorff) who might be able to provide some suggestions that are more Stata specific.

**Comment by syclik** [comment]
There's a setting in Travis to not build when the configuration file is missing. 

I have no idea why that's not the default for new repos. 

Anyway, I think we should just do that and enable Travis only if there's a config file. We should just remove the config file from this pull request. Sound ok?

**Comment by wbuchanan** [comment]
@syclik Totally fine with me.  I just removed the fake config file and pushed the change to my repository.  Let me know if there's anything you need me to do.

**Comment by syclik** [comment]
Thanks. I don't need anything else on my end.

@robertgrant action is to you.

**Pull request merged**
