### PR TITLE
Create distribution page

### PR DESCRIPTION
**Pull request by wbuchanan**
If the merge creates the gh-pages branch Stata users should be able to use:

```
net inst statastan, from("http://standev.github.io/statastan/")
```

To install the program directly from the gh-pages branch on GitHub.  Other than pulling and merging changes into the gh-pages branch on new releases, the only other maintenance would be updating the `Distribution-Date` field in the statastan.pkg file (as well as making sure the file listing is still accurate).

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Thanks much for creating the pull request.  I'm afraid I don't know Stata or Travis enough to sort out the integration issue.

**Comment by robertgrant** [comment]
I'm away from home now so I'll take a closer look tomorrow but I notice that same Travis message exists on the master and obsolete alpha-test branches too... so I don't know what it's exactly telling us. The -stan- command is going to SSC soon, so I think the value of this is in giving people access to the unstable dev version rather than periodic releases (which can go to SSC), and should be on the master branch not gh-pages. Does that make sense?

If it all looks OK, I'll merge into master tomorrow.

**Comment by wbuchanan** [comment]
Net installing from the master branch isn't quite as straight forward.  The URL needs to point to the stata.toc file which is what Stata is using with the net install command.  From there, the entry in that file (statastan) in this case, is used to find the package file (statastan.pkg) with the same name to locate files that will be installed and ancillary files.  The gh-pages branch sets up a fairly straight forward HTTP access point to avoid having to deal with the having to figure out installing directly from master.  I could probably throw something together that could do it all a bit more automatically and some other people have made similar attempts at building interfaces for GitHub that may be useful in that event.

**Comment by bob-carpenter** [comment]
@syclik or @ariddell --- any idea what's up with Travis here?

**Comment by wbuchanan** [comment]
@bob-carpenter it may be an issue with the [languages supported by TravisCI](https://docs.travis-ci.com/user/languages/) and/or an attempt to classify the files based on extension (e.g., like the .pkg file) without recognizing the context (e.g., Stata vs a *nix .pkg file)

**Comment by robertgrant** [comment]
I suspect it just doesn't get along with Stata .pkg, but don't know that for sure. Thanks @wbuchanan for clarifying the role of gh-pages for me. I'll wait for advice from more expert stan-dev git users before attempting anything. I guess if all else fails I can just manually replicate your gh-pages branch file by file...

**Comment by robertgrant** [comment]
I made the gh-pages branch. Try pulling again and we'll see if the Travis issue is still there.

**Pull request closed without merging**
